In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

image = cv2.imread('./robotics/top.png')

#cv2.imshow('image',image)
#cv2.waitKey(0)
#cv2.destroyAllWindows()

In [2]:
# Get red square
# Define range for red color
lower_red = np.array([0, 0, 100]) # this may vary
upper_red = np.array([50, 50, 255]) # this may vary
lower_blue = np.array([100, 0, 0]) # this may vary
upper_blue = np.array([255, 50, 50]) # this may vary

# Create a mask to filter only red pixels
mask = cv2.inRange(image, lower_red, upper_red)

# Bitwise-AND mask and with your image 
red_pixels = cv2.bitwise_and(image, image, mask=mask)

# All the red pixels will be in the red_pixels image 
# Non-red pixels will be black.

#cv2.imshow('red_pixels', red_pixels)
#cv2.waitKey(0)
#cv2.destroyAllWindows()

In [3]:
# Source: https://www.tutorialspoint.com/how-to-detect-a-rectangle-and-square-in-an-image-using-opencv-python
image = image # the top down view
img = red_pixels # only red pixels
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

ret,thresh = cv2.threshold(gray,50,255,0)
contours,hierarchy = cv2.findContours(thresh, 1, 2)
print("Number of contours detected:", len(contours))

target_point = []
for cnt in contours:
    x1,y1 = cnt[0][0]
    approx = cv2.approxPolyDP(cnt, 0.01*cv2.arcLength(cnt, True), True)
    if len(approx) == 4:
        print("square")
        x, y, w, h = cv2.boundingRect(cnt)
        target_point = (x+w//2, y+h//2)

     
        img = cv2.drawContours(image, [cnt], -1, (0,255,255), 3)
        cv2.putText(img, 'Target', (x1, y1), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 0), 2)

# The target center point is:

#cv2.imshow("Shapes", img)
#cv2.waitKey(0)
#cv2.destroyAllWindows()

print(target_point)

Number of contours detected: 3
square
(1060, 422)


In [4]:

#cv2.imshow("Shapes", red_pixels)
#cv2.waitKey(0)
#cv2.destroyAllWindows()

In [5]:
matrix = [
  [1, 1, 1],
  [1, 0, 1],
  [1, 1, 1]
]

In [6]:
# replace all black with 1 (=walkable) in red pixels
red_pixels[red_pixels <= lower_red[2]] = 1
matrix=red_pixels[:,:,2]
matrix

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=uint8)

In [7]:
# convert image to grid: obstacles = 0, driveable = 1

In [8]:
target_point

(1060, 422)

In [9]:
matrix[0][0]

1

In [10]:
# https://github.com/brean/python-pathfinding
from pathfinding.core.diagonal_movement import DiagonalMovement
from pathfinding.core.grid import Grid
from pathfinding.finder.a_star import AStarFinder




#matrix = image
grid = Grid(matrix=matrix)
#target_point = (2, 2)

grid

<Grid width=1523 height=1038>

In [11]:
img.shape

(1038, 1523, 3)

In [12]:
red_pixels.shape[0],red_pixels.shape[1]//2

(1038, 761)

In [13]:
start = grid.node(red_pixels.shape[1]//2-1,red_pixels.shape[0]-1) # TODO SET THIS TO CENTER BOTTOM ???
end = grid.node(*target_point)
start

<GridNode(760:1037 0x22ec03d11f0)>

In [14]:
finder = AStarFinder(diagonal_movement=DiagonalMovement.never)
path, runs = finder.find_path(start, end, grid)


In [15]:
for step in path:
    print(step.x, step.y)

760 1037
760 1036
760 1035
760 1034
760 1033
760 1032
760 1031
760 1030
760 1029
760 1028
760 1027
760 1026
760 1025
760 1024
760 1023
760 1022
760 1021
760 1020
760 1019
760 1018
760 1017
760 1016
760 1015
760 1014
760 1013
760 1012
760 1011
760 1010
760 1009
760 1008
760 1007
760 1006
760 1005
760 1004
760 1003
760 1002
760 1001
760 1000
760 999
760 998
760 997
760 996
760 995
760 994
760 993
760 992
760 991
760 990
760 989
760 988
760 987
760 986
760 985
760 984
760 983
760 982
760 981
760 980
760 979
760 978
760 977
760 976
760 975
760 974
760 973
760 972
760 971
760 970
760 969
760 968
760 967
760 966
760 965
760 964
760 963
760 962
760 961
760 960
760 959
760 958
760 957
760 956
760 955
760 954
760 953
760 952
760 951
760 950
760 949
760 948
760 947
760 946
760 945
760 944
760 943
760 942
760 941
760 940
760 939
760 938
760 937
760 936
760 935
760 934
760 933
760 932
760 931
760 930
760 929
760 928
760 927
760 926
760 925
760 924
760 923
760 922
760 921
760 920
760 919
760 918
76

In [16]:

#print(grid.grid_str(path=path, start=start, end=end))

In [17]:
for step in path:
    image[step.y][step.x] = [0,200,0]
    

In [18]:
#cv2.imshow("Shapes", img)
#cv2.waitKey(0)
#cv2.destroyAllWindows()



In [19]:
cv2.imwrite("path.png", img)

True

In [20]:
start

<GridNode(760:1037 0x22ec03d11f0)>

In [21]:
img.shape

(1038, 1523, 3)

In [22]:
path

[<GridNode(760:1037 0x22ec03d11f0)>,
 <GridNode(760:1036 0x22ec0377320)>,
 <GridNode(760:1035 0x22ec032d490)>,
 <GridNode(760:1034 0x22ec02d35c0)>,
 <GridNode(760:1033 0x22ec0289730)>,
 <GridNode(760:1032 0x22ec022f860)>,
 <GridNode(760:1031 0x22ec01e59d0)>,
 <GridNode(760:1030 0x22ec018bb00)>,
 <GridNode(760:1029 0x22ec0141c70)>,
 <GridNode(760:1028 0x22ec00e7da0)>,
 <GridNode(760:1027 0x22ec009df10)>,
 <GridNode(760:1026 0x22ec0054080)>,
 <GridNode(760:1025 0x22ebfffa1b0)>,
 <GridNode(760:1024 0x22ebffb0320)>,
 <GridNode(760:1023 0x22ebff52450)>,
 <GridNode(760:1022 0x22ebff085c0)>,
 <GridNode(760:1021 0x22ebfeae6f0)>,
 <GridNode(760:1020 0x22ebfe64860)>,
 <GridNode(760:1019 0x22ebfe0a990)>,
 <GridNode(760:1018 0x22ebfdc0b00)>,
 <GridNode(760:1017 0x22ebfd66c30)>,
 <GridNode(760:1016 0x22ebfd1cda0)>,
 <GridNode(760:1015 0x22ebfcc2ed0)>,
 <GridNode(760:1014 0x22ebfc79040)>,
 <GridNode(760:1013 0x22ebfc1f170)>,
 <GridNode(760:1012 0x22ebfbd52e0)>,
 <GridNode(760:1011 0x22ebfb7b410)>,
 

In [23]:
target_point

(1060, 422)

In [34]:
image_with_blue = cv2.imread('./topdown_blue.png')
image_with_blue.shape

(1038, 1523, 3)

In [35]:
# Create a mask to filter only red pixels
mask = cv2.inRange(image_with_blue, lower_blue, upper_blue)

# Bitwise-AND mask and with your image 
blue_pixels = cv2.bitwise_and(image_with_blue, image_with_blue, mask=mask)

blue_pixels_1_d = blue_pixels[:,:,0]

In [38]:
blue_pixels_1_d

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [37]:
cv2.imshow("Shapes", blue_pixels_1_d)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [44]:
cv2.imshow("Shapes", matrix)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [43]:
matrix[blue_pixels_1_d > 0] = 255



cv2.imshow("Shapes", matrix)
cv2.waitKey(0)
cv2.destroyAllWindows()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [50]:
cv2.imshow("Shapes", matrix)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [45]:
#matrix = image
grid = Grid(matrix=matrix)
#target_point = (2, 2)

grid

<Grid width=1523 height=1038>

In [46]:
start = grid.node(red_pixels.shape[1]//2-1,red_pixels.shape[0]-1) # TODO SET THIS TO CENTER BOTTOM ???
end = grid.node(*target_point)
start

<GridNode(760:1037 0x22ee09774a0)>

In [47]:
finder = AStarFinder(diagonal_movement=DiagonalMovement.never)
path, runs = finder.find_path(start, end, grid)


In [48]:
for step in path:
    image_with_blue[step.y][step.x] = [0,200,0]

In [49]:
cv2.imshow("Shapes", image_with_blue)
cv2.waitKey(0)
cv2.destroyAllWindows()